baseurl = "http://eestec.be"
languageCode = "be-nl"
title = "EESTEC Antwerpen"

[params]
    #ProfilePicture = "/img/logo.png"
    Description    = "Welcome to EESTEC's only LC in Belgium, proudly located in Antwerp!"
    #twitter        = "https://twitter.com/eestecantwerp"
    twittername    = "eestecantwerp"
    facebook       = "https://www.facebook.com/eestecantwerp"
    #email          = "board[at]eestec[dot]be"
    #showcase       = "Hello"
    #rss            = "/index.xml"
