baseurl = "http://eestec.be"
languageCode = "en-us"
title = "EESTEC Antwerpen"

[params]
    ProfilePicture = "/img/logo.png"
    Description    = ""
    twitter        = "https://twitter.com/eestecantwerp"
    twittername    = "eestecantwerp"
    facebook       = "https://www.facebook.com/eestecantwerp"
    email          = "board[at]eestec[dot]be"
    showcase       = ""
    rss            = "/index.xml"
