baseurl = "http://www.eestec.be"
languageCode = "be-nl"
title = "EESTEC Antwerpen"
theme = "herring-cove"
copyright = "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-sa/4.0/80x15.png\" /></a> This work by <a xmlns:cc=\"http://creativecommons.org/ns#\" href=\"www.eestec.be\" property=\"cc:attributionName\" rel=\"cc:attributionURL\">EESTEC Antwerp</a> is licensed under a <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\">Creative Commons Attribution-ShareAlike 4.0 International License</a>."

[params]
    description    = "LC Antwerpen"
    logo           = "/img/logo.svg"
    twitter        = "https://twitter.com/eestecantwerp"
    facebook       = "https://www.facebook.com/eestecantwerp"
    showcase       = "Welcome to the EESTEC Antwerp website!"
    rss            = "/rss"
    contact        = "/contact"
    [links]
        Home                = "/"
        About               = "/about/"
        Board               = "/board/"
        Vakantiewerk        = "/vakantiewerk/"
