baseurl = "http://www.eestec.be"
languageCode = "be-nl"
title = "EESTEC Antwerpen"

[params]
    profilepicture = "/img/logo.png"
    description    = ""
    twitter        = "https://twitter.com/eestecantwerp"
    facebook       = "https://www.facebook.com/eestecantwerp"
    showcase       = "Welcome to the EESTEC Antwerp website!"
    rss            = "/rss"
